# Generated by Django 3.1.6 on 2021-11-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='site_media/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('parent_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.figure')),
            ],
        ),
    ]
