# Generated by Django 3.1.6 on 2021-11-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='parent_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.figure'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
