# Generated by Django 3.1.6 on 2021-11-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20211126_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='picture',
            field=models.ImageField(blank=True, upload_to='site_media/'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
